service: crystal-inventory-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  profile: dan-personal

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
plugins:
  - serverless-plugin-typescript
